### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by billbogaiv**
Ref. #28.

### CODE REVIEW

**Comment by billbogaiv** [comment]
Removed WIP after getting successful confirmation of config.

Ref. https://travis-ci.org/ritterim/releases/builds/98186606

**Comment by billbogaiv** [comment]
Config. copied and modified from [dnx repo.](https://github.com/aspnet/dnx/blob/3e9166ef2cd6b6915d16a16bb7a69b7826c571f3/.travis.yml)

**Comment by khalidabuhakmeh** [comment]
Could you add the badge to the `Readme.md` file in this commit?

**Comment by billbogaiv** [comment]
@khalidabuhakmeh: done

image

**Pull request merged**
